/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cn.lgs.semevosql.evolution.application;

import cn.lgs.semevosql.evolution.application.SemanticChangeSetApplicationService.ChangeSet;
import cn.lgs.semevosql.evolution.application.SemanticChangeSetApplicationService.CreateCommand;
import cn.lgs.semevosql.evolution.domain.EvolutionRootCause;
import cn.lgs.semevosql.evolution.domain.SemanticVersionPolicy.Trigger;
import cn.lgs.semevosql.util.JsonUtil;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

/** Records corpus/source changes independently from Semantic Version numbering. */
@Service
@RequiredArgsConstructor
public class CorpusRevisionApplicationService {

    private final JdbcTemplate jdbc;

    private final SemanticVersionApplicationService versionService;

    private final SemanticChangeSetApplicationService changeSetService;

    @Transactional
    public CorpusRevision record(RecordCommand command) {
        require(command.projectId(), "projectId");
        requireText(command.sourceType(), "sourceType");
        requireText(command.idempotencyKey(), "idempotencyKey");
        requireText(command.createdBy(), "createdBy");
        List<CorpusRevision> existing = jdbc.query("""
                SELECT * FROM qw_corpus_revision WHERE project_id = ? AND idempotency_key = ?
                """, this::map, command.projectId(), command.idempotencyKey());
        if (!existing.isEmpty()) {
            CorpusRevision revision = existing.get(0);
            if (!Objects.equals(revision.contentHash(), command.contentHash())) {
                throw new IllegalStateException("Corpus Revision idempotency key is bound to different content");
            }
            return revision;
        }
        // Project row is the narrow serialization point for revision_no allocation.
        Integer locked = jdbc.query("SELECT id FROM qw_project WHERE id = ? FOR UPDATE",
                (rs, rowNum) -> rs.getInt(1), command.projectId()).stream().findFirst()
            .orElseThrow(() -> new IllegalArgumentException("Semantic project not found: " + command.projectId()));
        if (locked == null) {
            throw new IllegalStateException("Unable to lock Semantic project");
        }
        Long nextRevision = jdbc.queryForObject("""
                SELECT COALESCE(MAX(revision_no), 0) + 1 FROM qw_corpus_revision WHERE project_id = ?
                """, Long.class, command.projectId());
        String changeSetId = null;
        if (command.semanticDiffDetected()) {
            Long activeVersionId = versionService.active(command.projectId()).semanticVersionId();
            ChangeSet changeSet = changeSetService.create(new CreateCommand(command.projectId(), activeVersionId,
                    Trigger.CORPUS_UPDATE, true, "CORPUS", command.sourceRef(), EvolutionRootCause.SEMANTIC_LAYER,
                    defaultText(command.riskLevel(), "MEDIUM"), "corpus:" + command.idempotencyKey(),
                    command.createdBy()));
            changeSetId = changeSet.changeSetId();
        }
        jdbc.update("""
                INSERT INTO qw_corpus_revision
                (project_id, revision_no, source_type, source_ref, content_hash, idempotency_key,
                 semantic_diff_detected, semantic_change_set_id, metadata_json, created_by)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS JSONB), ?)
                """, command.projectId(), nextRevision, command.sourceType(), command.sourceRef(), command.contentHash(),
                command.idempotencyKey(), command.semanticDiffDetected(), changeSetId, json(command.metadata()),
                command.createdBy());
        // id is generated by the database; fetch by the unique idempotency key.
        return jdbc.query("SELECT * FROM qw_corpus_revision WHERE project_id = ? AND idempotency_key = ?", this::map,
                command.projectId(), command.idempotencyKey()).stream().findFirst().orElseThrow();
    }

    public Optional<CorpusRevision> findByIdempotency(Long projectId, String idempotencyKey) {
        if (projectId == null || !StringUtils.hasText(idempotencyKey)) {
            return Optional.empty();
        }
        return jdbc.query("""
                SELECT * FROM qw_corpus_revision WHERE project_id = ? AND idempotency_key = ?
                """, this::map, projectId, idempotencyKey).stream().findFirst();
    }

    public List<CorpusRevision> list(Long projectId) {
        return jdbc.query("""
                SELECT * FROM qw_corpus_revision WHERE project_id = ? ORDER BY revision_no DESC
                """, this::map, projectId);
    }

    private CorpusRevision map(java.sql.ResultSet rs, int rowNum) throws java.sql.SQLException {
        return new CorpusRevision(rs.getLong("id"), rs.getLong("project_id"), rs.getLong("revision_no"),
                rs.getString("source_type"), rs.getString("source_ref"), rs.getString("content_hash"),
                rs.getString("idempotency_key"), rs.getBoolean("semantic_diff_detected"),
                rs.getString("semantic_change_set_id"), rs.getString("created_by"),
                local(rs.getTimestamp("create_time")));
    }

    private String json(Object value) {
        try {
            return JsonUtil.getObjectMapper().writeValueAsString(value == null ? Map.of() : value);
        }
        catch (Exception ex) {
            throw new IllegalArgumentException("Unable to serialize Corpus Revision metadata", ex);
        }
    }

    private String defaultText(String value, String fallback) {
        return StringUtils.hasText(value) ? value.trim() : fallback;
    }

    private void require(Object value, String field) {
        if (value == null) {
            throw new IllegalArgumentException(field + " is required");
        }
    }

    private void requireText(String value, String field) {
        if (!StringUtils.hasText(value)) {
            throw new IllegalArgumentException(field + " is required");
        }
    }

    private LocalDateTime local(java.sql.Timestamp value) {
        return value == null ? null : value.toLocalDateTime();
    }

    public record RecordCommand(Long projectId, String sourceType, String sourceRef, String contentHash,
            String idempotencyKey, boolean semanticDiffDetected, String riskLevel, Map<String, Object> metadata,
            String createdBy) {
    }

    public record CorpusRevision(Long id, Long projectId, Long revisionNo, String sourceType, String sourceRef,
            String contentHash, String idempotencyKey, boolean semanticDiffDetected, String semanticChangeSetId,
            String createdBy, LocalDateTime createTime) {
    }
}
