ALTER TABLE qw_runtime_clarification
    ADD COLUMN selected_scope VARCHAR(32);

ALTER TABLE qw_runtime_clarification_answer
    ADD COLUMN selected_scope VARCHAR(32);

CREATE TABLE qw_user_semantic_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    user_id VARCHAR(128) NOT NULL,
    normalized_phrase VARCHAR(500) NOT NULL,
    display_phrase VARCHAR(500) NOT NULL,
    asset_type VARCHAR(64) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    business_label VARCHAR(500) NOT NULL,
    hit_count BIGINT NOT NULL DEFAULT 0,
    correction_count BIGINT NOT NULL DEFAULT 0,
    next_upgrade_prompt_at BIGINT NOT NULL DEFAULT 10,
    upgrade_prompt_pending BOOLEAN NOT NULL DEFAULT FALSE,
    upgrade_dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_time TIMESTAMP,
    CONSTRAINT uk_qw_user_semantic_preference UNIQUE(project_id, user_id, normalized_phrase)
);
CREATE INDEX idx_qw_user_semantic_preference_user
    ON qw_user_semantic_preference(project_id, user_id, update_time DESC);

CREATE TABLE qw_project_semantic_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    normalized_phrase VARCHAR(500) NOT NULL,
    display_phrase VARCHAR(500) NOT NULL,
    asset_type VARCHAR(64) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    business_label VARCHAR(500) NOT NULL,
    evidence TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_project_semantic_alias UNIQUE(project_id, normalized_phrase)
);
CREATE INDEX idx_qw_project_semantic_alias_project
    ON qw_project_semantic_alias(project_id, status);

CREATE TABLE qw_user_semantic_preference_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preference_id BIGINT NOT NULL REFERENCES qw_user_semantic_preference(id) ON DELETE CASCADE,
    run_id VARCHAR(64),
    event_type VARCHAR(32) NOT NULL,
    valid BOOLEAN NOT NULL DEFAULT TRUE,
    idempotency_key VARCHAR(200) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_user_semantic_preference_usage UNIQUE(idempotency_key)
);
CREATE INDEX idx_qw_user_semantic_preference_usage_preference
    ON qw_user_semantic_preference_usage(preference_id, valid, event_type);
