-- Copyright 2024-2026 the original author or authors.
-- Licensed under the Apache License, Version 2.0.

CREATE TABLE qw_project_version_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    activity_type VARCHAR(32) NOT NULL,
    operator_name VARCHAR(255) NOT NULL,
    operator_role VARCHAR(32) NOT NULL,
    request_id VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_qw_project_version_activity_type CHECK (activity_type IN ('PUBLISHED', 'ACTIVATED')),
    CONSTRAINT uk_qw_project_version_activity_idempotency UNIQUE(activity_type, project_version_id, idempotency_key)
);

CREATE INDEX idx_qw_project_version_activity_version
    ON qw_project_version_activity(project_id, project_version_id, activity_type, create_time DESC);
