CREATE TABLE qw_project_mcp_deployment (
    deployment_id VARCHAR(36) PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE RESTRICT,
    catalog_hash CHAR(64) NOT NULL,
    principal_id VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL,
    endpoint VARCHAR(1024) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_time TIMESTAMP,
    last_recovered_time TIMESTAMP,
    CONSTRAINT uk_qw_project_mcp_deployment_project UNIQUE(project_id),
    CONSTRAINT uk_qw_project_mcp_deployment_principal UNIQUE(principal_id)
);
CREATE INDEX idx_qw_project_mcp_deployment_status ON qw_project_mcp_deployment(status);

CREATE TABLE qw_project_mcp_credential (
    credential_id VARCHAR(36) PRIMARY KEY,
    deployment_id VARCHAR(36) NOT NULL REFERENCES qw_project_mcp_deployment(deployment_id) ON DELETE CASCADE,
    token_prefix VARCHAR(32) NOT NULL,
    secret_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMP,
    revoked_at TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_project_mcp_credential_prefix UNIQUE(token_prefix)
);
CREATE INDEX idx_qw_project_mcp_credential_active ON qw_project_mcp_credential(deployment_id, revoked_at, expires_at);

CREATE TABLE qw_external_query_handle (
    query_id VARCHAR(36) PRIMARY KEY,
    deployment_id VARCHAR(36) NOT NULL REFERENCES qw_project_mcp_deployment(deployment_id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    conversation_id VARCHAR(64),
    run_id VARCHAR(64) REFERENCES qw_query_run(run_id) ON DELETE CASCADE,
    state VARCHAR(16) NOT NULL DEFAULT 'RESERVED',
    request_fingerprint CHAR(64) NOT NULL,
    last_error VARCHAR(1024),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_external_query_retry UNIQUE(deployment_id, request_fingerprint)
);
CREATE INDEX idx_qw_external_query_handle_run ON qw_external_query_handle(run_id);

CREATE TABLE qw_project_mcp_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployment_id VARCHAR(36),
    project_id BIGINT,
    principal_id VARCHAR(128),
    action VARCHAR(64) NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    detail VARCHAR(1024),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_qw_project_mcp_audit_project_time ON qw_project_mcp_audit(project_id, create_time DESC);
