CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- Core application metadata. QueryWeaver uses PostgreSQL as its internal fact store;
-- datasource rows still describe external business databases of any supported dialect.
CREATE TABLE agent (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    avatar TEXT,
    status VARCHAR(50) DEFAULT 'draft',
    api_key VARCHAR(255),
    api_key_enabled SMALLINT DEFAULT 0,
    prompt TEXT,
    category VARCHAR(100),
    admin_id BIGINT,
    tags TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_agent_name ON agent(name);
CREATE INDEX idx_agent_status ON agent(status);
CREATE INDEX idx_agent_category ON agent(category);
CREATE INDEX idx_agent_admin_id ON agent(admin_id);

CREATE TABLE business_knowledge (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_term VARCHAR(255) NOT NULL,
    description TEXT,
    synonyms TEXT,
    is_recall INTEGER DEFAULT 1,
    agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    embedding_status VARCHAR(20),
    error_msg VARCHAR(255),
    is_deleted INTEGER DEFAULT 0
);
CREATE INDEX idx_business_knowledge_business_term ON business_knowledge(business_term);
CREATE INDEX idx_business_knowledge_agent_id ON business_knowledge(agent_id);

CREATE TABLE semantic_model (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
    datasource_id INTEGER NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    column_name VARCHAR(255) NOT NULL DEFAULT '',
    business_name VARCHAR(255) NOT NULL DEFAULT '',
    synonyms TEXT,
    business_description TEXT,
    column_comment VARCHAR(255),
    data_type VARCHAR(255) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_semantic_model_agent_id ON semantic_model(agent_id);
CREATE INDEX idx_semantic_model_business_name ON semantic_model(business_name);
CREATE INDEX idx_semantic_model_status ON semantic_model(status);

CREATE TABLE agent_knowledge (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    question TEXT,
    content TEXT,
    is_recall INTEGER DEFAULT 1,
    embedding_status VARCHAR(20),
    error_msg VARCHAR(255),
    source_filename VARCHAR(500),
    file_path VARCHAR(500),
    file_size BIGINT,
    file_type VARCHAR(255),
    splitter_type VARCHAR(50) DEFAULT 'token',
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted INTEGER DEFAULT 0,
    is_resource_cleaned INTEGER DEFAULT 0
);
CREATE INDEX idx_agent_knowledge_agent_id_status ON agent_knowledge(agent_id, is_recall);
CREATE INDEX idx_agent_knowledge_embedding_status ON agent_knowledge(embedding_status);
CREATE INDEX idx_agent_knowledge_is_deleted ON agent_knowledge(is_deleted);

CREATE TABLE datasource (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL,
    database_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    connection_url VARCHAR(1000),
    status VARCHAR(50) DEFAULT 'inactive',
    test_status VARCHAR(50) DEFAULT 'unknown',
    description TEXT,
    creator_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_datasource_name ON datasource(name);
CREATE INDEX idx_datasource_type ON datasource(type);
CREATE INDEX idx_datasource_status ON datasource(status);
CREATE INDEX idx_datasource_creator_id ON datasource(creator_id);

CREATE TABLE logical_relation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id) ON DELETE CASCADE,
    source_table_name VARCHAR(100) NOT NULL,
    source_column_name VARCHAR(100) NOT NULL,
    target_table_name VARCHAR(100) NOT NULL,
    target_column_name VARCHAR(100) NOT NULL,
    relation_type VARCHAR(20),
    description VARCHAR(500),
    is_deleted SMALLINT DEFAULT 0,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_logical_relation_datasource_id ON logical_relation(datasource_id);
CREATE INDEX idx_logical_relation_source_table ON logical_relation(datasource_id, source_table_name);

CREATE TABLE agent_datasource (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id) ON DELETE CASCADE,
    is_active SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_datasource UNIQUE(agent_id, datasource_id)
);
CREATE INDEX idx_agent_datasource_agent_id ON agent_datasource(agent_id);
CREATE INDEX idx_agent_datasource_datasource_id ON agent_datasource(datasource_id);

CREATE TABLE agent_preset_question (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT FALSE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_session (
    id VARCHAR(36) PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
    title VARCHAR(255) DEFAULT '新对话',
    status VARCHAR(50) DEFAULT 'active',
    is_pinned BOOLEAN DEFAULT FALSE,
    user_id BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chat_session_agent_id ON chat_session(agent_id);
CREATE INDEX idx_chat_session_user_id ON chat_session(user_id);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    message_type VARCHAR(50) DEFAULT 'text',
    metadata JSONB,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chat_message_session_id ON chat_message(session_id);

CREATE TABLE user_prompt_config (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    prompt_type VARCHAR(100) NOT NULL,
    agent_id INTEGER,
    system_prompt TEXT NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    description TEXT,
    priority INTEGER DEFAULT 0,
    display_order INTEGER DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    creator VARCHAR(255)
);

CREATE TABLE agent_datasource_tables (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_datasource_id INTEGER NOT NULL REFERENCES agent_datasource(id) ON UPDATE CASCADE ON DELETE CASCADE,
    table_name VARCHAR(255) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_datasource_tables UNIQUE(agent_datasource_id, table_name)
);

CREATE TABLE model_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(255) NOT NULL,
    base_url VARCHAR(255) NOT NULL,
    api_key VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    temperature DECIMAL(10,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT FALSE,
    max_tokens INTEGER DEFAULT 2000,
    model_type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
    completions_path VARCHAR(255),
    embeddings_path VARCHAR(255),
    created_time TIMESTAMP,
    updated_time TIMESTAMP,
    is_deleted INTEGER DEFAULT 0,
    proxy_enabled BOOLEAN DEFAULT FALSE,
    proxy_host VARCHAR(255),
    proxy_port INTEGER,
    proxy_username VARCHAR(255),
    proxy_password VARCHAR(255)
);

-- QueryWeaver semantic project aggregate.
CREATE TABLE qw_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    business_domain VARCHAR(128) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL,
    active_version_id BIGINT,
    created_by VARCHAR(128) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revision BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_qw_project_code UNIQUE(project_code)
);
CREATE INDEX idx_qw_project_status ON qw_project(status);

CREATE TABLE qw_project_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL,
    version_number VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    parent_version_id BIGINT REFERENCES qw_project_version(id) ON DELETE RESTRICT,
    creation_mode VARCHAR(16) NOT NULL DEFAULT 'BLANK',
    initialization_model_id BIGINT,
    analysis_status VARCHAR(32) NOT NULL,
    analysis_error TEXT,
    source VARCHAR(255),
    evidence TEXT,
    catalog_hash CHAR(64),
    release_report JSONB,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validated_time TIMESTAMP,
    published_time TIMESTAMP,
    revision BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_qw_project_version UNIQUE(project_id, version_no),
    CONSTRAINT uk_qw_project_version_number UNIQUE(project_id, version_number)
);
CREATE INDEX idx_qw_project_version_status ON qw_project_version(project_id, status);
CREATE INDEX idx_qw_project_version_parent ON qw_project_version(project_id, parent_version_id);

CREATE TABLE qw_project_datasource_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id) ON DELETE RESTRICT,
    domain_code VARCHAR(128) NOT NULL,
    domain_name VARCHAR(255) NOT NULL,
    responsibility TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_project_datasource UNIQUE(project_version_id, datasource_id)
);
CREATE INDEX idx_qw_project_datasource_priority ON qw_project_datasource_binding(project_id, project_version_id, priority, id);

CREATE TABLE qw_project_datasource_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_id BIGINT NOT NULL REFERENCES qw_project_datasource_binding(id) ON DELETE CASCADE,
    table_name VARCHAR(255) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_project_datasource_table UNIQUE(binding_id, table_name)
);

CREATE TABLE qw_semantic_gap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    gap_key VARCHAR(255),
    gap_type VARCHAR(64) NOT NULL,
    question TEXT NOT NULL,
    recommendation TEXT,
    evidence TEXT,
    impact_scope TEXT,
    priority INTEGER NOT NULL DEFAULT 100,
    status VARCHAR(32) NOT NULL,
    answer TEXT,
    resolved_by VARCHAR(128),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_time TIMESTAMP,
    CONSTRAINT uk_qw_gap_key UNIQUE(project_version_id, gap_key)
);
CREATE INDEX idx_qw_gap_next ON qw_semantic_gap(project_id, project_version_id, status, priority, id);

CREATE TABLE qw_project_runtime_profile (
    project_id BIGINT PRIMARY KEY REFERENCES qw_project(id) ON DELETE CASCADE,
    runtime_profile_id VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_semantic_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id) ON DELETE RESTRICT,
    model_code VARCHAR(128) NOT NULL,
    physical_table VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    model_type VARCHAR(32),
    description TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_model_code UNIQUE(project_version_id, model_code),
    CONSTRAINT uk_qw_semantic_model_table UNIQUE(project_version_id, datasource_id, physical_table)
);
CREATE INDEX idx_qw_semantic_model_project ON qw_semantic_model(project_id, project_version_id, status);

CREATE TABLE qw_semantic_column (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    model_code VARCHAR(128) NOT NULL,
    column_name VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    data_type VARCHAR(128),
    role VARCHAR(32),
    expression TEXT,
    synonyms TEXT,
    description TEXT,
    nullable_flag BOOLEAN,
    sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    masking_policy VARCHAR(32) NOT NULL DEFAULT 'NONE',
    allow_aggregation BOOLEAN NOT NULL DEFAULT TRUE,
    allow_filter BOOLEAN NOT NULL DEFAULT TRUE,
    allow_projection BOOLEAN NOT NULL DEFAULT TRUE,
    allow_export BOOLEAN NOT NULL DEFAULT TRUE,
    allow_send_to_llm BOOLEAN NOT NULL DEFAULT TRUE,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_column UNIQUE(project_version_id, model_code, column_name)
);
CREATE INDEX idx_qw_semantic_column_model ON qw_semantic_column(project_id, project_version_id, model_code, status);

CREATE TABLE qw_semantic_metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    model_code VARCHAR(128) NOT NULL,
    metric_code VARCHAR(128) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    expression TEXT NOT NULL,
    aggregation VARCHAR(64),
    unit VARCHAR(64),
    time_column VARCHAR(255),
    filter_expression TEXT,
    additive_type VARCHAR(64),
    description TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_metric UNIQUE(project_version_id, metric_code)
);
CREATE INDEX idx_qw_semantic_metric_model ON qw_semantic_metric(project_id, project_version_id, model_code, status);

CREATE TABLE qw_semantic_dimension (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    model_code VARCHAR(128) NOT NULL,
    dimension_code VARCHAR(128) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    column_name VARCHAR(255),
    expression TEXT,
    dimension_type VARCHAR(64),
    hierarchy TEXT,
    description TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_dimension UNIQUE(project_version_id, dimension_code)
);
CREATE INDEX idx_qw_semantic_dimension_model ON qw_semantic_dimension(project_id, project_version_id, model_code, status);

CREATE TABLE qw_semantic_relationship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    relationship_code VARCHAR(128) NOT NULL,
    source_model_code VARCHAR(128) NOT NULL,
    target_model_code VARCHAR(128) NOT NULL,
    cardinality VARCHAR(32) NOT NULL,
    join_type VARCHAR(32),
    join_condition TEXT NOT NULL,
    description TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_relationship UNIQUE(project_version_id, relationship_code)
);
CREATE INDEX idx_qw_semantic_relationship_models ON qw_semantic_relationship(project_id, project_version_id, source_model_code, target_model_code, status);

CREATE TABLE qw_semantic_grain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    model_code VARCHAR(128) NOT NULL,
    grain_code VARCHAR(128) NOT NULL,
    key_columns JSONB NOT NULL,
    time_column VARCHAR(255),
    uniqueness_rule TEXT,
    description TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_grain UNIQUE(project_version_id, model_code, grain_code)
);

CREATE TABLE qw_semantic_enum_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    model_code VARCHAR(128) NOT NULL,
    column_name VARCHAR(255) NOT NULL,
    value_code VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    aliases JSONB,
    description TEXT,
    sort_order INTEGER,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_enum_value UNIQUE(project_version_id, model_code, column_name, value_code)
);

CREATE TABLE qw_semantic_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    model_code VARCHAR(128),
    rule_code VARCHAR(128) NOT NULL,
    rule_type VARCHAR(64) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    expression TEXT NOT NULL,
    severity VARCHAR(32),
    description TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_rule UNIQUE(project_version_id, rule_code)
);

CREATE TABLE qw_logical_column_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    logical_entity_code VARCHAR(128) NOT NULL,
    logical_attribute_code VARCHAR(128) NOT NULL,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id),
    model_code VARCHAR(128) NOT NULL,
    column_name VARCHAR(255),
    expression TEXT,
    transform_rule TEXT,
    grain_code VARCHAR(128),
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_logical_column_binding UNIQUE(project_version_id, logical_entity_code, logical_attribute_code, datasource_id)
);
CREATE INDEX idx_qw_logical_column_binding_model ON qw_logical_column_binding(project_id, project_version_id, datasource_id, model_code, status);

CREATE TABLE qw_authority_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    logical_asset_type VARCHAR(32) NOT NULL,
    logical_asset_code VARCHAR(128) NOT NULL,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id),
    source_role VARCHAR(32) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100,
    allow_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    condition_expression TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_authority_rule UNIQUE(project_version_id, logical_asset_type, logical_asset_code, datasource_id)
);
CREATE INDEX idx_qw_authority_rule_selection ON qw_authority_rule(project_id, project_version_id, logical_asset_type, logical_asset_code, source_role, priority);

CREATE TABLE qw_freshness_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    datasource_id INTEGER NOT NULL REFERENCES datasource(id),
    business_date_field VARCHAR(255) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    freshness_type VARCHAR(32) NOT NULL,
    latency_minutes INTEGER NOT NULL,
    available_until_rule TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_freshness_policy UNIQUE(project_version_id, datasource_id)
);

CREATE TABLE qw_cross_source_relationship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    relationship_code VARCHAR(128) NOT NULL,
    left_datasource_id INTEGER NOT NULL REFERENCES datasource(id),
    left_model_code VARCHAR(128) NOT NULL,
    left_key VARCHAR(255) NOT NULL,
    right_datasource_id INTEGER NOT NULL REFERENCES datasource(id),
    right_model_code VARCHAR(128) NOT NULL,
    right_key VARCHAR(255) NOT NULL,
    cardinality VARCHAR(32) NOT NULL,
    transform_rule TEXT,
    null_policy VARCHAR(64) NOT NULL,
    uniqueness_rule TEXT NOT NULL,
    confidence INTEGER NOT NULL,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_cross_source_relationship UNIQUE(project_version_id, relationship_code)
);

CREATE TABLE qw_merge_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    policy_code VARCHAR(128) NOT NULL,
    merge_type VARCHAR(64) NOT NULL,
    relationship_code VARCHAR(128),
    left_input_key VARCHAR(255),
    right_input_key VARCHAR(255),
    output_key VARCHAR(255),
    input_grain VARCHAR(255),
    null_policy VARCHAR(64) NOT NULL,
    duplicate_policy VARCHAR(64) NOT NULL,
    max_rows INTEGER NOT NULL,
    partial_failure_policy VARCHAR(64) NOT NULL,
    calculation_expression TEXT,
    evidence TEXT,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_merge_policy UNIQUE(project_version_id, policy_code)
);

CREATE TABLE qw_query_run (
    run_id VARCHAR(64) PRIMARY KEY,
    run_type VARCHAR(32) NOT NULL,
    project_id BIGINT,
    project_version_id BIGINT,
    episode_id VARCHAR(64),
    attempt_id VARCHAR(64),
    thread_id VARCHAR(160),
    status VARCHAR(32) NOT NULL,
    current_node VARCHAR(128),
    last_event_sequence BIGINT NOT NULL DEFAULT 0,
    request_id VARCHAR(160),
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    owner_instance VARCHAR(160),
    lease_expire_time TIMESTAMP,
    start_time TIMESTAMP,
    finish_time TIMESTAMP,
    error_code VARCHAR(128),
    error_message TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    request_payload TEXT,
    recovery_payload TEXT,
    execution_snapshot TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_qw_run_recovery ON qw_query_run(status, lease_expire_time);
CREATE INDEX idx_qw_run_project ON qw_query_run(project_id, project_version_id);

CREATE TABLE qw_source_sub_run (
    sub_run_id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL REFERENCES qw_query_run(run_id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id),
    datasource_id INTEGER NOT NULL REFERENCES datasource(id),
    status VARCHAR(32) NOT NULL,
    source_plan_json JSONB NOT NULL,
    sql_text TEXT,
    result_artifact_id VARCHAR(64),
    row_count BIGINT,
    freshness_as_of VARCHAR(128),
    error_message TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finish_time TIMESTAMP,
    CONSTRAINT uk_qw_source_sub_run UNIQUE(run_id, datasource_id)
);

CREATE TABLE qw_result_artifact (
    artifact_id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL REFERENCES qw_query_run(run_id) ON DELETE CASCADE,
    source_sub_run_id VARCHAR(64) REFERENCES qw_source_sub_run(sub_run_id) ON DELETE CASCADE,
    artifact_type VARCHAR(32) NOT NULL,
    schema_json JSONB NOT NULL,
    data_json JSONB NOT NULL,
    row_count BIGINT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_result_artifact_source UNIQUE(source_sub_run_id)
);

CREATE TABLE qw_merge_execution (
    merge_id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL REFERENCES qw_query_run(run_id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id),
    policy_code VARCHAR(128),
    policy_json JSONB,
    status VARCHAR(32) NOT NULL,
    input_artifacts_json JSONB,
    output_artifact_id VARCHAR(64),
    error_message TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finish_time TIMESTAMP,
    CONSTRAINT uk_qw_merge_execution_run UNIQUE(run_id)
);

CREATE TABLE qw_project_conversation (
    conversation_id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_project_message (
    message_id VARCHAR(64) PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL REFERENCES qw_project_conversation(conversation_id) ON DELETE CASCADE,
    sequence_no BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    run_id VARCHAR(64) REFERENCES qw_query_run(run_id) ON DELETE SET NULL,
    status VARCHAR(32) NOT NULL,
    metadata_json JSONB,
    idempotency_key VARCHAR(160),
    request_fingerprint CHAR(64),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_project_message_sequence UNIQUE(conversation_id, sequence_no),
    CONSTRAINT uk_qw_project_message_idempotency UNIQUE(conversation_id, idempotency_key)
);

CREATE TABLE qw_semantic_material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    document_type VARCHAR(64) NOT NULL,
    material_type VARCHAR(32) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_material_id BIGINT REFERENCES qw_semantic_material(id) ON DELETE SET NULL,
    source_name VARCHAR(500),
    original_filename VARCHAR(500),
    media_type VARCHAR(255),
    file_path VARCHAR(1000),
    file_size BIGINT,
    source_location VARCHAR(1000),
    datasource_id INTEGER,
    content_hash CHAR(64) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    parse_summary TEXT,
    error_message TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_material_hash UNIQUE(project_version_id, content_hash)
);

CREATE TABLE qw_semantic_material_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES qw_semantic_material(id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    source_location VARCHAR(1000),
    extraction_model VARCHAR(255),
    parse_summary TEXT,
    error_message TEXT,
    start_time TIMESTAMP NOT NULL,
    finish_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_material_attempt UNIQUE(material_id, attempt_no)
);

CREATE TABLE qw_semantic_asset_provenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    material_id BIGINT NOT NULL REFERENCES qw_semantic_material(id) ON DELETE CASCADE,
    attempt_id BIGINT NOT NULL REFERENCES qw_semantic_material_attempt(id) ON DELETE CASCADE,
    asset_type VARCHAR(32) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    asset_fingerprint CHAR(64) NOT NULL,
    disposition VARCHAR(32) NOT NULL,
    conflict_gap_key VARCHAR(255),
    confidence DECIMAL(6,4) NOT NULL,
    source_location VARCHAR(1000),
    extraction_model VARCHAR(255),
    evidence TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_asset_provenance UNIQUE(attempt_id, asset_type, asset_key)
);

CREATE TABLE qw_episode (
    id VARCHAR(64) PRIMARY KEY,
    request_id VARCHAR(128) NOT NULL UNIQUE,
    agent_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    datasource_id INTEGER,
    catalog_hash CHAR(64) NOT NULL,
    original_question TEXT NOT NULL,
    normalized_question TEXT,
    status VARCHAR(32) NOT NULL,
    model_name VARCHAR(128),
    prompt_version VARCHAR(64),
    error_type VARCHAR(64),
    token_count BIGINT,
    duration_ms BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_attempt (
    id VARCHAR(64) PRIMARY KEY,
    episode_id VARCHAR(64) NOT NULL,
    attempt_no INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_type VARCHAR(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_attempt_no UNIQUE(episode_id, attempt_no)
);

CREATE TABLE qw_node_trace (
    id VARCHAR(64) PRIMARY KEY,
    attempt_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_summary TEXT,
    output_summary TEXT,
    decision_summary TEXT,
    effect_summary TEXT,
    contribution_score DECIMAL(8,4),
    cost_json JSONB,
    result_proof_json JSONB,
    reused BOOLEAN NOT NULL DEFAULT FALSE,
    correction_type VARCHAR(64),
    duration_ms BIGINT,
    error_type VARCHAR(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_node_trace_key UNIQUE(attempt_id, idempotency_key)
);

CREATE TABLE qw_sql_trace (
    id VARCHAR(64) PRIMARY KEY,
    attempt_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    sql_text TEXT,
    guard_summary TEXT,
    cost_summary TEXT,
    explain_summary TEXT,
    preview_summary TEXT,
    result_summary TEXT,
    status VARCHAR(32) NOT NULL,
    retry_count INTEGER DEFAULT 0,
    duration_ms BIGINT,
    error_type VARCHAR(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_sql_trace_key UNIQUE(attempt_id, idempotency_key)
);

CREATE TABLE qw_feedback (
    id VARCHAR(64) PRIMARY KEY,
    episode_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    rating INTEGER,
    adopted BOOLEAN,
    comment_text TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_query_example (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    catalog_hash CHAR(64) NOT NULL,
    datasource_id INTEGER,
    episode_id VARCHAR(64) NOT NULL,
    attempt_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64),
    context_hash CHAR(64),
    original_question TEXT,
    normalized_question TEXT NOT NULL,
    intent_type VARCHAR(64),
    conversation_independent BOOLEAN NOT NULL DEFAULT TRUE,
    resolved_time_range_json JSONB,
    typed_ir_json JSONB,
    resolution_json JSONB,
    quality_proof_json JSONB,
    result_schema_hash CHAR(64),
    canonical_shape_hash CHAR(64),
    sql_text TEXT NOT NULL,
    sql_hash CHAR(64) NOT NULL,
    historical_sql_text TEXT,
    fingerprint CHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    rebind_status VARCHAR(32) NOT NULL DEFAULT 'VALID',
    source_example_id VARCHAR(64),
    derived_from_case_ids JSONB,
    root_evidence_ids JSONB,
    evidence_lineage_hash CHAR(64),
    quality_summary TEXT,
    reviewed_by VARCHAR(128),
    review_comment TEXT,
    recall_count BIGINT NOT NULL DEFAULT 0,
    adopted_count BIGINT NOT NULL DEFAULT 0,
    failed_after_recall_count BIGINT NOT NULL DEFAULT 0,
    consecutive_recall_issue_count BIGINT NOT NULL DEFAULT 0,
    quarantine_reason TEXT,
    quarantine_time TIMESTAMP,
    last_recalled_time TIMESTAMP,
    reviewed_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_qw_query_example_recall ON qw_query_example(project_id, project_version_id, status, rebind_status, reviewed_time);
CREATE INDEX idx_qw_query_example_shape ON qw_query_example(project_id, project_version_id, intent_type, canonical_shape_hash);

CREATE TABLE qw_query_case_term (
    query_example_id VARCHAR(64) NOT NULL,
    term VARCHAR(64) NOT NULL,
    term_frequency INTEGER NOT NULL,
    document_length INTEGER NOT NULL,
    PRIMARY KEY(query_example_id, term)
);
CREATE INDEX idx_qw_query_case_term_lookup ON qw_query_case_term(term, query_example_id);

CREATE TABLE qw_query_case_embedding (
    query_example_id VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(255) NOT NULL,
    embedding_version VARCHAR(64) NOT NULL DEFAULT 'v1',
    content_hash CHAR(64) NOT NULL,
    dimension INTEGER NOT NULL,
    embedding vector NOT NULL,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(query_example_id, embedding_model, embedding_version)
);
CREATE INDEX idx_qw_query_case_embedding_hash ON qw_query_case_embedding(embedding_model, embedding_version, content_hash);

CREATE TABLE qw_query_case_event (
    id VARCHAR(64) PRIMARY KEY,
    query_example_id VARCHAR(64) NOT NULL,
    sequence BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    actor VARCHAR(128) NOT NULL,
    actor_source VARCHAR(32) NOT NULL,
    payload JSONB NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_case_event_sequence UNIQUE(query_example_id, sequence)
);
CREATE INDEX idx_qw_query_case_event_type ON qw_query_case_event(query_example_id, event_type, create_time);

CREATE TABLE qw_golden_case (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    case_code VARCHAR(128) NOT NULL,
    question TEXT NOT NULL,
    replay_mode VARCHAR(16) NOT NULL DEFAULT 'LIVE',
    dataset_version VARCHAR(128),
    expected_json JSONB NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_golden_case UNIQUE(project_id, case_code)
);

CREATE TABLE qw_evaluation_job (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64),
    project_id BIGINT NOT NULL,
    project_version_id BIGINT,
    job_type VARCHAR(32) NOT NULL,
    candidate_id VARCHAR(64),
    idempotency_key VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL,
    progress INTEGER DEFAULT 0,
    current_case_id VARCHAR(64),
    current_level VARCHAR(32),
    checkpoint_json JSONB,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    request_json JSONB,
    result_json JSONB,
    error_message TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_time TIMESTAMP,
    CONSTRAINT uk_qw_job_key UNIQUE(project_id, idempotency_key)
);

CREATE TABLE qw_release (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    baseline_version_id BIGINT NOT NULL,
    candidate_version_id BIGINT NOT NULL,
    release_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    traffic_percent INTEGER DEFAULT 0,
    policy_version VARCHAR(64),
    sample_count BIGINT DEFAULT 0,
    failure_count BIGINT DEFAULT 0,
    metrics_json JSONB,
    rollback_reason TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_onboarding_session (
    session_id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed_by VARCHAR(128),
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    confirmation_idempotency_key VARCHAR(160),
    confirmation_revision BIGINT,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    complete_time TIMESTAMP,
    CONSTRAINT uk_qw_onboarding_version UNIQUE(project_id, project_version_id)
);

CREATE TABLE qw_onboarding_coverage (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    category VARCHAR(64) NOT NULL,
    requirement VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    satisfied_by VARCHAR(64),
    evidence TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_onboarding_coverage UNIQUE(session_id, category)
);

CREATE TABLE qw_onboarding_question (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    category VARCHAR(64) NOT NULL,
    question TEXT NOT NULL,
    recommended_answer TEXT,
    recommendation_reason TEXT,
    evidence TEXT,
    answer_schema JSONB,
    blocking BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL,
    depends_on JSONB,
    status VARCHAR(32) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_onboarding_answer (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    question_id VARCHAR(64) NOT NULL,
    category VARCHAR(64) NOT NULL,
    answer TEXT NOT NULL,
    answer_type VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    answered_by VARCHAR(128) NOT NULL,
    question_revision BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_onboarding_answer_key UNIQUE(question_id, idempotency_key)
);

CREATE TABLE qw_onboarding_conflict (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    conflict_type VARCHAR(64) NOT NULL,
    message TEXT NOT NULL,
    evidence TEXT,
    blocking BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(32) NOT NULL,
    resolution_question_id VARCHAR(64),
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_thread_execution_guard (
    thread_id VARCHAR(160) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_conversation_turn (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    thread_id VARCHAR(160) NOT NULL,
    turn_sequence BIGINT NOT NULL,
    user_question TEXT NOT NULL,
    planner_output TEXT,
    status VARCHAR(32) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_conversation_sequence UNIQUE(thread_id, turn_sequence)
);

CREATE TABLE qw_run_event (
    run_id VARCHAR(64) NOT NULL,
    sequence BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    node_name VARCHAR(128),
    payload TEXT,
    payload_summary TEXT,
    idempotency_key VARCHAR(200) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(run_id, sequence),
    CONSTRAINT uk_qw_run_event_key UNIQUE(run_id, idempotency_key)
);

CREATE TABLE qw_run_checkpoint (
    run_id VARCHAR(64) PRIMARY KEY,
    thread_id VARCHAR(160),
    current_node VARCHAR(128),
    state_json TEXT,
    completed_node_keys TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_run_node_effect (
    effect_id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    node_key VARCHAR(255) NOT NULL,
    input_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    result_json TEXT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    complete_time TIMESTAMP,
    CONSTRAINT uk_qw_run_node_effect UNIQUE(run_id, node_key)
);

CREATE TABLE qw_run_subscription (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    subscriber_id VARCHAR(160) NOT NULL,
    last_delivered_sequence BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_run_subscription UNIQUE(run_id, subscriber_id)
);

CREATE TABLE qw_runtime_clarification (
    clarification_id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    question TEXT NOT NULL,
    options_json JSONB NOT NULL,
    recommended_option VARCHAR(160),
    reason TEXT,
    evidence TEXT,
    issue_type VARCHAR(64),
    asset_type VARCHAR(64),
    asset_key VARCHAR(500),
    raw_expression TEXT,
    resolved_value TEXT,
    resolution_source VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    selected_option VARCHAR(160),
    custom_answer TEXT,
    answered_by VARCHAR(128),
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_runtime_clarification_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clarification_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    selected_option VARCHAR(160),
    custom_answer TEXT,
    answered_by VARCHAR(128) NOT NULL,
    clarification_revision BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_clarification_answer UNIQUE(clarification_id, idempotency_key)
);

CREATE TABLE qw_query_pattern (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    catalog_hash CHAR(64) NOT NULL,
    execution_compatibility_hash CHAR(64) NOT NULL,
    shape_hash CHAR(64) NOT NULL,
    instance_hash CHAR(64) NOT NULL,
    intent_type VARCHAR(64) NOT NULL,
    pattern_json JSONB NOT NULL,
    ambiguity_level VARCHAR(32) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    episode_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'OBSERVE_ONLY',
    first_seen_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_pattern UNIQUE(project_version_id, execution_compatibility_hash, shape_hash)
);

CREATE TABLE qw_trajectory_path (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    episode_id VARCHAR(64) NOT NULL,
    attempt_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64),
    pattern_id VARCHAR(64) NOT NULL,
    execution_compatibility_hash CHAR(64) NOT NULL,
    path_signature CHAR(64) NOT NULL,
    node_sequence_json JSONB NOT NULL,
    decision_sequence_json JSONB NOT NULL,
    source_sequence_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    correctness_score DECIMAL(8,4) NOT NULL,
    safety_score DECIMAL(8,4) NOT NULL,
    coverage_score DECIMAL(8,4) NOT NULL,
    freshness_score DECIMAL(8,4) NOT NULL,
    stability_score DECIMAL(8,4) NOT NULL,
    latency_ms BIGINT,
    token_count BIGINT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    clarification_count INTEGER NOT NULL DEFAULT 0,
    source_count INTEGER NOT NULL DEFAULT 0,
    merge_count INTEGER NOT NULL DEFAULT 0,
    cost_json JSONB NOT NULL,
    result_proof_json JSONB NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_trajectory_attempt UNIQUE(attempt_id)
);

CREATE TABLE qw_query_path_profile (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    pattern_id VARCHAR(64) NOT NULL,
    execution_compatibility_hash CHAR(64) NOT NULL,
    path_signature CHAR(64) NOT NULL,
    sample_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    correctness_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    safety_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    coverage_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    freshness_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    stability_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    avg_latency_ms DECIMAL(18,4) NOT NULL DEFAULT 0,
    avg_token_count DECIMAL(18,4) NOT NULL DEFAULT 0,
    avg_retry_count DECIMAL(18,4) NOT NULL DEFAULT 0,
    avg_clarification_count DECIMAL(18,4) NOT NULL DEFAULT 0,
    dominated BOOLEAN NOT NULL DEFAULT FALSE,
    pareto_rank INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'OBSERVE_ONLY',
    last_evaluated_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_path_profile UNIQUE(pattern_id, execution_compatibility_hash, path_signature)
);

CREATE TABLE qw_detour_signal (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    pattern_id VARCHAR(64) NOT NULL,
    path_id VARCHAR(64) NOT NULL,
    signal_type VARCHAR(64) NOT NULL,
    root_cause VARCHAR(64) NOT NULL,
    issue_type VARCHAR(64),
    asset_type VARCHAR(64),
    asset_key VARCHAR(500),
    signal_fingerprint CHAR(64) NOT NULL,
    confidence DECIMAL(8,4) NOT NULL,
    occurrence_count BIGINT NOT NULL DEFAULT 1,
    recurrence_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
    evidence_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OBSERVE_ONLY',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_detour_signal UNIQUE(path_id, signal_fingerprint)
);

CREATE TABLE qw_semantic_evolution_candidate (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_version_id BIGINT NOT NULL,
    source_catalog_hash CHAR(64) NOT NULL,
    candidate_type VARCHAR(64) NOT NULL,
    asset_type VARCHAR(64) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    status VARCHAR(32) NOT NULL,
    confidence DECIMAL(8,4) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    patch_json JSONB NOT NULL,
    patch_hash CHAR(64),
    evidence_summary TEXT NOT NULL,
    mapping_classification VARCHAR(32),
    evidence_distribution_json JSONB,
    distinct_conversation_count BIGINT NOT NULL DEFAULT 0,
    distinct_user_count BIGINT,
    distinct_root_evidence_count BIGINT NOT NULL DEFAULT 0,
    distinct_time_window_count BIGINT NOT NULL DEFAULT 0,
    target_draft_version_id BIGINT,
    applied_time TIMESTAMP,
    replay_summary_json JSONB,
    rebind_status VARCHAR(32),
    rebind_error TEXT,
    reviewed_by VARCHAR(128),
    review_comment TEXT,
    reviewed_time TIMESTAMP,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_candidate UNIQUE(source_version_id, source_catalog_hash, candidate_type, asset_type, asset_key, status)
);

CREATE TABLE qw_candidate_evidence (
    id VARCHAR(64) PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    evidence_type VARCHAR(64) NOT NULL,
    episode_id VARCHAR(64),
    path_id VARCHAR(64),
    detour_signal_id VARCHAR(64),
    weight DECIMAL(8,4) NOT NULL,
    evidence_json JSONB NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_candidate_evidence UNIQUE(candidate_id, evidence_type, episode_id, path_id, detour_signal_id)
);

CREATE TABLE qw_semantic_evolution_event (
    id VARCHAR(64) PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    sequence BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    actor VARCHAR(128) NOT NULL,
    actor_source VARCHAR(32) NOT NULL,
    request_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    source_version_id BIGINT,
    target_version_id BIGINT,
    patch_hash CHAR(64),
    replay_run_id VARCHAR(64),
    payload JSONB NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_event_sequence UNIQUE(candidate_id, sequence),
    CONSTRAINT uk_qw_semantic_event_idempotency UNIQUE(candidate_id, idempotency_key)
);

CREATE TABLE qw_runtime_optimization_candidate (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    pattern_id VARCHAR(64) NOT NULL,
    execution_compatibility_hash CHAR(64) NOT NULL,
    optimization_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    applicability_json JSONB NOT NULL,
    proposal_json JSONB NOT NULL,
    baseline_metrics_json JSONB NOT NULL,
    shadow_metrics_json JSONB,
    confidence DECIMAL(8,4) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    reviewed_by VARCHAR(128),
    review_comment TEXT,
    reviewed_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_runtime_candidate UNIQUE(pattern_id, execution_compatibility_hash, optimization_type, status)
);

CREATE TABLE qw_preferred_execution_plan (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    pattern_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(64) NOT NULL,
    execution_compatibility_hash CHAR(64) NOT NULL,
    plan_json JSONB NOT NULL,
    applicability_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    enabled_time TIMESTAMP,
    disabled_reason TEXT,
    revision BIGINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_preferred_plan UNIQUE(pattern_id, execution_compatibility_hash, status)
);

CREATE TABLE qw_query_example_asset_ref (
    id VARCHAR(64) PRIMARY KEY,
    query_example_id VARCHAR(64) NOT NULL,
    asset_type VARCHAR(64) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    asset_fingerprint CHAR(64),
    catalog_hash CHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_example_asset UNIQUE(query_example_id, asset_type, asset_key)
);

CREATE TABLE qw_query_example_rebind (
    id VARCHAR(64) PRIMARY KEY,
    source_example_id VARCHAR(64) NOT NULL,
    target_version_id BIGINT NOT NULL,
    target_catalog_hash CHAR(64) NOT NULL,
    target_example_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    reasons_json JSONB NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_example_rebind UNIQUE(source_example_id, target_version_id, target_catalog_hash)
);

CREATE TABLE qw_query_case_usage (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    query_example_id VARCHAR(64) NOT NULL,
    recalled BOOLEAN NOT NULL DEFAULT TRUE,
    adopted BOOLEAN NOT NULL DEFAULT FALSE,
    failed_after_recall BOOLEAN NOT NULL DEFAULT FALSE,
    outcome VARCHAR(32),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_case_usage UNIQUE(run_id, query_example_id)
);

CREATE TABLE qw_semantic_replay_result (
    id VARCHAR(64) PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    replay_execution_id VARCHAR(64) NOT NULL,
    target_version_id BIGINT NOT NULL,
    case_id VARCHAR(64) NOT NULL,
    replay_level VARCHAR(32) NOT NULL,
    replay_mode VARCHAR(16),
    dataset_version VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    baseline_json JSONB,
    candidate_json JSONB,
    proof_json JSONB NOT NULL,
    error_message TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_replay UNIQUE(candidate_id, replay_execution_id, case_id, replay_level)
);

CREATE TABLE qw_manual_attestation (
    id VARCHAR(64) PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    attestation_type VARCHAR(32) NOT NULL,
    decision VARCHAR(32) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    actor_source VARCHAR(32) NOT NULL,
    reason TEXT NOT NULL,
    risk_acceptance TEXT,
    related_replay_run_id VARCHAR(64),
    alternative_proof_json JSONB,
    idempotency_key VARCHAR(160) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_manual_attestation UNIQUE(candidate_id, idempotency_key)
);

CREATE TABLE qw_release_decision (
    id VARCHAR(64) PRIMARY KEY,
    candidate_id VARCHAR(64) NOT NULL,
    automated_result VARCHAR(32) NOT NULL,
    manual_attestation_id VARCHAR(64),
    decision VARCHAR(16) NOT NULL,
    policy_code VARCHAR(64) NOT NULL,
    reason TEXT NOT NULL,
    decided_by VARCHAR(128) NOT NULL,
    related_replay_run_id VARCHAR(64),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qw_evaluation_case_result (
    id VARCHAR(64) PRIMARY KEY,
    evaluation_job_id VARCHAR(64) NOT NULL,
    golden_case_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    correctness_score DECIMAL(8,4) NOT NULL DEFAULT 0,
    safety_score DECIMAL(8,4) NOT NULL DEFAULT 0,
    latency_ms BIGINT,
    token_count BIGINT,
    result_proof_json JSONB NOT NULL,
    error_message TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_evaluation_case_result UNIQUE(evaluation_job_id, golden_case_id)
);
