-- SemEvoSQL domain migration: immutable Semantic Version snapshots, Corpus Revision,
-- SemanticChangeSet workspace, richer Episode lineage and project-scoped MCP deployments.
--
-- This migration is intentionally additive/compatibility-first. Legacy columns remain while
-- runtime code is migrated away from Draft-Version workspaces and deployment-time version pins.

-- -----------------------------------------------------------------------------
-- Semantic Version metadata
-- -----------------------------------------------------------------------------
ALTER TABLE qw_project_version
    ADD COLUMN semantic_major INTEGER,
    ADD COLUMN semantic_minor INTEGER,
    ADD COLUMN semantic_patch INTEGER,
    ADD COLUMN version_level VARCHAR(16),
    ADD COLUMN version_cause VARCHAR(64),
    ADD COLUMN semantic_state_hash CHAR(64),
    ADD COLUMN corpus_revision_id BIGINT,
    ADD COLUMN activated_time TIMESTAMP,
    ADD COLUMN deactivated_time TIMESTAMP;

UPDATE qw_project_version
SET semantic_major = CASE
        WHEN version_number ~ '^[0-9]+\.[0-9]+\.[0-9]+$' THEN split_part(version_number, '.', 1)::INTEGER
        ELSE 0
    END,
    semantic_minor = CASE
        WHEN version_number ~ '^[0-9]+\.[0-9]+\.[0-9]+$' THEN split_part(version_number, '.', 2)::INTEGER
        ELSE 0
    END,
    semantic_patch = CASE
        WHEN version_number ~ '^[0-9]+\.[0-9]+\.[0-9]+$' THEN split_part(version_number, '.', 3)::INTEGER
        ELSE version_no
    END,
    semantic_state_hash = COALESCE(catalog_hash, repeat('0', 64));

ALTER TABLE qw_project_version
    ALTER COLUMN semantic_major SET NOT NULL,
    ALTER COLUMN semantic_minor SET NOT NULL,
    ALTER COLUMN semantic_patch SET NOT NULL;

ALTER TABLE qw_project_version
    ADD CONSTRAINT ck_qw_project_version_semver_non_negative
        CHECK (semantic_major >= 0 AND semantic_minor >= 0 AND semantic_patch >= 0),
    ADD CONSTRAINT ck_qw_project_version_level
        CHECK (version_level IS NULL OR version_level IN ('PATCH', 'MINOR', 'MAJOR', 'INITIAL'));

CREATE UNIQUE INDEX uk_qw_project_version_semver
    ON qw_project_version(project_id, semantic_major, semantic_minor, semantic_patch);

CREATE INDEX idx_qw_project_version_semantic_state
    ON qw_project_version(project_id, semantic_state_hash);

-- -----------------------------------------------------------------------------
-- Corpus Revision: records what business/source assets the project has seen.
-- It advances independently from Semantic Version when the corpus changes without semantic diff.
-- -----------------------------------------------------------------------------
CREATE TABLE qw_corpus_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    revision_no BIGINT NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_ref VARCHAR(512),
    content_hash CHAR(64),
    idempotency_key VARCHAR(160) NOT NULL,
    semantic_diff_detected BOOLEAN NOT NULL DEFAULT FALSE,
    semantic_change_set_id VARCHAR(64),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by VARCHAR(128) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_corpus_revision UNIQUE(project_id, revision_no),
    CONSTRAINT uk_qw_corpus_revision_idempotency UNIQUE(project_id, idempotency_key)
);
CREATE INDEX idx_qw_corpus_revision_project_time
    ON qw_corpus_revision(project_id, create_time DESC);

-- Link Semantic Version to the corpus revision it was derived from after the table exists.
ALTER TABLE qw_project_version
    ADD CONSTRAINT fk_qw_project_version_corpus_revision
        FOREIGN KEY (corpus_revision_id) REFERENCES qw_corpus_revision(id) ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- SemanticChangeSet: mutable evolution workspace. Semantic Version itself remains snapshot data.
-- -----------------------------------------------------------------------------
CREATE TABLE qw_semantic_change_set (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    base_semantic_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE RESTRICT,
    target_version_level VARCHAR(16) NOT NULL,
    origin_type VARCHAR(32) NOT NULL,
    origin_ref VARCHAR(128),
    root_cause VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    semantic_diff_hash CHAR(64),
    replay_run_id VARCHAR(64),
    replay_summary_json JSONB,
    validation_summary_json JSONB,
    affected_asset_count INTEGER NOT NULL DEFAULT 0,
    materialized_version_id BIGINT REFERENCES qw_project_version(id) ON DELETE SET NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(128) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_time TIMESTAMP,
    CONSTRAINT ck_qw_semantic_change_set_level CHECK (target_version_level IN ('PATCH', 'MINOR', 'MAJOR')),
    CONSTRAINT ck_qw_semantic_change_set_origin CHECK (origin_type IN ('EPISODE', 'CORPUS', 'MANUAL', 'BASELINE_PROMOTION')),
    CONSTRAINT ck_qw_semantic_change_set_status CHECK (status IN (
        'DRAFT', 'VALIDATING', 'REPLAYING', 'INDEXING', 'READY', 'ACTIVATING', 'ACTIVE', 'REJECTED', 'FAILED', 'STALE'
    )),
    CONSTRAINT uk_qw_semantic_change_set_idempotency UNIQUE(project_id, idempotency_key)
);
CREATE INDEX idx_qw_semantic_change_set_project_status
    ON qw_semantic_change_set(project_id, status, create_time DESC);
CREATE INDEX idx_qw_semantic_change_set_base_version
    ON qw_semantic_change_set(base_semantic_version_id, create_time DESC);

CREATE TABLE qw_semantic_change_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_set_id VARCHAR(64) NOT NULL REFERENCES qw_semantic_change_set(id) ON DELETE CASCADE,
    asset_type VARCHAR(64) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    operation VARCHAR(16) NOT NULL,
    before_hash CHAR(64),
    after_hash CHAR(64),
    patch_json JSONB NOT NULL,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_qw_semantic_change_item_operation CHECK (operation IN ('ADD', 'UPDATE', 'DELETE')),
    CONSTRAINT uk_qw_semantic_change_item UNIQUE(change_set_id, asset_type, asset_key)
);
CREATE INDEX idx_qw_semantic_change_item_asset
    ON qw_semantic_change_item(asset_type, asset_key);

ALTER TABLE qw_semantic_evolution_candidate
    ADD COLUMN semantic_change_set_id VARCHAR(64)
        REFERENCES qw_semantic_change_set(id) ON DELETE SET NULL;
CREATE INDEX idx_qw_semantic_evolution_candidate_change_set
    ON qw_semantic_evolution_candidate(semantic_change_set_id);

ALTER TABLE qw_semantic_replay_result
    ALTER COLUMN candidate_id DROP NOT NULL,
    ALTER COLUMN target_version_id DROP NOT NULL,
    ADD COLUMN change_set_id VARCHAR(64)
        REFERENCES qw_semantic_change_set(id) ON DELETE SET NULL;
CREATE INDEX idx_qw_semantic_replay_result_change_set
    ON qw_semantic_replay_result(change_set_id, replay_execution_id);

ALTER TABLE qw_corpus_revision
    ADD CONSTRAINT fk_qw_corpus_revision_change_set
        FOREIGN KEY (semantic_change_set_id) REFERENCES qw_semantic_change_set(id) ON DELETE SET NULL;

CREATE TABLE qw_semantic_activation_event (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    from_version_id BIGINT REFERENCES qw_project_version(id) ON DELETE SET NULL,
    to_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE RESTRICT,
    change_set_id VARCHAR(64) REFERENCES qw_semantic_change_set(id) ON DELETE SET NULL,
    event_type VARCHAR(32) NOT NULL,
    reason VARCHAR(1024),
    actor VARCHAR(128) NOT NULL,
    request_id VARCHAR(128),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_qw_semantic_activation_event_type CHECK (event_type IN ('ACTIVATE', 'ROLLBACK', 'REBASE'))
);
CREATE INDEX idx_qw_semantic_activation_event_project
    ON qw_semantic_activation_event(project_id, create_time DESC);

-- -----------------------------------------------------------------------------
-- Episode: experience unit. Keep project_version_id/catalog_hash as legacy mirrors while
-- base_semantic_version_id/accepted_semantic_state_hash become the explicit pinned snapshot.
-- -----------------------------------------------------------------------------
ALTER TABLE qw_episode
    ADD COLUMN conversation_id VARCHAR(64),
    ADD COLUMN parent_episode_id VARCHAR(64),
    ADD COLUMN relation_type VARCHAR(32),
    ADD COLUMN base_semantic_version_id BIGINT,
    ADD COLUMN accepted_semantic_state_hash CHAR(64),
    ADD COLUMN result_semantic_version_id BIGINT,
    ADD COLUMN outcome VARCHAR(32),
    ADD COLUMN idempotency_key VARCHAR(160),
    ADD COLUMN request_fingerprint VARCHAR(160),
    ADD COLUMN accepted_attempt_id VARCHAR(64),
    ADD COLUMN completed_time TIMESTAMP;

UPDATE qw_episode
SET base_semantic_version_id = project_version_id,
    accepted_semantic_state_hash = catalog_hash,
    idempotency_key = request_id,
    request_fingerprint = request_id,
    outcome = CASE
        WHEN status = 'SUCCEEDED' THEN 'SUCCEEDED'
        WHEN status = 'FAILED' THEN 'FAILED'
        ELSE NULL
    END;

ALTER TABLE qw_episode
    ALTER COLUMN base_semantic_version_id SET NOT NULL,
    ALTER COLUMN accepted_semantic_state_hash SET NOT NULL,
    ALTER COLUMN idempotency_key SET NOT NULL,
    ALTER COLUMN request_fingerprint SET NOT NULL,
    ADD CONSTRAINT fk_qw_episode_parent
        FOREIGN KEY (parent_episode_id) REFERENCES qw_episode(id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_qw_episode_base_semantic_version
        FOREIGN KEY (base_semantic_version_id) REFERENCES qw_project_version(id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_qw_episode_result_semantic_version
        FOREIGN KEY (result_semantic_version_id) REFERENCES qw_project_version(id) ON DELETE SET NULL,
    ADD CONSTRAINT ck_qw_episode_relation_type
        CHECK (relation_type IS NULL OR relation_type IN ('FOLLOW_UP', 'DRILL_DOWN', 'EXPLAIN', 'NEW_GOAL', 'REBASE'));

CREATE UNIQUE INDEX uk_qw_episode_project_idempotency
    ON qw_episode(project_id, idempotency_key);
CREATE INDEX idx_qw_episode_conversation
    ON qw_episode(project_id, conversation_id, create_time);
CREATE INDEX idx_qw_episode_parent
    ON qw_episode(parent_episode_id);
CREATE INDEX idx_qw_episode_base_version
    ON qw_episode(base_semantic_version_id, create_time DESC);

CREATE TABLE qw_episode_turn (
    id VARCHAR(64) PRIMARY KEY,
    episode_id VARCHAR(64) NOT NULL REFERENCES qw_episode(id) ON DELETE CASCADE,
    turn_no INTEGER NOT NULL,
    turn_type VARCHAR(32) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    request_id VARCHAR(128),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_qw_episode_turn_type CHECK (turn_type IN (
        'QUESTION', 'CLARIFICATION_REQUEST', 'CLARIFICATION_RESPONSE', 'CORRECTION', 'RETRY', 'RESUME', 'RESULT', 'FEEDBACK'
    )),
    CONSTRAINT uk_qw_episode_turn_no UNIQUE(episode_id, turn_no)
);
CREATE INDEX idx_qw_episode_turn_episode_time ON qw_episode_turn(episode_id, create_time);

CREATE TABLE qw_episode_signal (
    id VARCHAR(64) PRIMARY KEY,
    episode_id VARCHAR(64) NOT NULL REFERENCES qw_episode(id) ON DELETE CASCADE,
    attempt_id VARCHAR(64),
    signal_type VARCHAR(64) NOT NULL,
    root_cause VARCHAR(64),
    confidence DECIMAL(8,4),
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_qw_episode_signal_episode ON qw_episode_signal(episode_id, create_time);
CREATE INDEX idx_qw_episode_signal_root_cause ON qw_episode_signal(root_cause, create_time DESC);

ALTER TABLE qw_attempt
    ADD COLUMN run_id VARCHAR(64),
    ADD COLUMN semantic_version_id BIGINT,
    ADD COLUMN semantic_state_hash CHAR(64),
    ADD COLUMN retrieval_generation VARCHAR(128),
    ADD COLUMN model_config_revision VARCHAR(128),
    ADD CONSTRAINT fk_qw_attempt_semantic_version
        FOREIGN KEY (semantic_version_id) REFERENCES qw_project_version(id) ON DELETE SET NULL;

UPDATE qw_attempt a
SET semantic_version_id = e.base_semantic_version_id,
    semantic_state_hash = e.accepted_semantic_state_hash
FROM qw_episode e
WHERE e.id = a.episode_id;

-- -----------------------------------------------------------------------------
-- Retrieval Index Generation: versioned by semantic state + embedding configuration.
-- -----------------------------------------------------------------------------
CREATE TABLE qw_retrieval_index_generation (
    id VARCHAR(128) PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES qw_project(id) ON DELETE CASCADE,
    semantic_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    semantic_state_hash CHAR(64) NOT NULL,
    embedding_config_hash CHAR(64) NOT NULL,
    rerank_config_hash CHAR(64),
    model_config_revision VARCHAR(128),
    status VARCHAR(24) NOT NULL,
    build_mode VARCHAR(24) NOT NULL,
    affected_asset_count INTEGER NOT NULL DEFAULT 0,
    indexed_asset_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(2048),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ready_time TIMESTAMP,
    CONSTRAINT ck_qw_retrieval_index_generation_status CHECK (status IN ('BUILDING', 'READY', 'FAILED', 'STALE')),
    CONSTRAINT ck_qw_retrieval_index_generation_mode CHECK (build_mode IN ('FULL', 'INCREMENTAL')),
    CONSTRAINT uk_qw_retrieval_index_generation UNIQUE(project_id, semantic_version_id, embedding_config_hash)
);
CREATE INDEX idx_qw_retrieval_index_generation_ready
    ON qw_retrieval_index_generation(project_id, status, ready_time DESC);

-- -----------------------------------------------------------------------------
-- MCP deployment becomes project-scoped. Legacy pin columns are retained nullable for rolling
-- compatibility, but new runtime code must resolve the project's Active Semantic Version per Episode.
-- -----------------------------------------------------------------------------
ALTER TABLE qw_project_mcp_deployment
    ALTER COLUMN project_version_id DROP NOT NULL,
    ALTER COLUMN catalog_hash DROP NOT NULL;

ALTER TABLE qw_external_query_handle
    ADD COLUMN episode_id VARCHAR(64),
    ADD COLUMN request_id VARCHAR(128),
    ADD COLUMN idempotency_key VARCHAR(160),
    ADD COLUMN semantic_version_id BIGINT,
    ADD CONSTRAINT fk_qw_external_query_handle_episode
        FOREIGN KEY (episode_id) REFERENCES qw_episode(id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_qw_external_query_handle_semantic_version
        FOREIGN KEY (semantic_version_id) REFERENCES qw_project_version(id) ON DELETE SET NULL;

UPDATE qw_external_query_handle
SET request_id = query_id,
    idempotency_key = request_fingerprint
WHERE request_id IS NULL;

ALTER TABLE qw_external_query_handle
    ALTER COLUMN request_id SET NOT NULL,
    ALTER COLUMN idempotency_key SET NOT NULL;

CREATE UNIQUE INDEX uk_qw_external_query_handle_idempotency
    ON qw_external_query_handle(deployment_id, idempotency_key);
CREATE INDEX idx_qw_external_query_handle_episode ON qw_external_query_handle(episode_id);
CREATE INDEX idx_qw_external_query_handle_semantic_version ON qw_external_query_handle(semantic_version_id);
