CREATE TABLE qw_query_case_binding_dependency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_example_id VARCHAR(64) NOT NULL REFERENCES qw_query_example(id) ON DELETE CASCADE,
    phrase VARCHAR(500),
    asset_type VARCHAR(64) NOT NULL,
    asset_key VARCHAR(500) NOT NULL,
    binding_scope VARCHAR(32) NOT NULL,
    binding_source VARCHAR(64) NOT NULL,
    principal_id VARCHAR(128),
    source_record_id BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_query_case_binding_dependency UNIQUE(
        query_example_id, asset_type, asset_key, binding_scope, binding_source, principal_id
    )
);
CREATE INDEX idx_qw_query_case_binding_dependency_case
    ON qw_query_case_binding_dependency(query_example_id);
CREATE INDEX idx_qw_query_case_binding_dependency_scope
    ON qw_query_case_binding_dependency(binding_scope, principal_id, query_example_id);

-- Backfill legacy Query Cases that already consumed a per-user preference.  This makes
-- pre-V31 approved cases obey the same principal boundary as newly captured cases.
INSERT INTO qw_query_case_binding_dependency
(query_example_id, phrase, asset_type, asset_key, binding_scope, binding_source, principal_id, source_record_id)
SELECT DISTINCT qe.id, p.display_phrase, p.asset_type, p.asset_key, 'USER', 'USER', p.user_id, p.id
FROM qw_query_example qe
JOIN qw_user_semantic_preference_usage u ON u.run_id = qe.run_id AND u.valid = TRUE
JOIN qw_user_semantic_preference p ON p.id = u.preference_id
WHERE qe.run_id IS NOT NULL
  AND u.event_type IN ('APPLIED', 'COUNTED')
ON CONFLICT DO NOTHING;

-- Clarifications are authoritative at the moment knowledge is created. Legacy QUERY
-- choices must never become historical project knowledge; legacy PROJECT choices remain
-- pending unless they subsequently entered the governed project-semantic release flow.
INSERT INTO qw_query_case_binding_dependency
(query_example_id, phrase, asset_type, asset_key, binding_scope, binding_source, principal_id, source_record_id)
SELECT DISTINCT qe.id,
       LEFT(COALESCE(NULLIF(c.raw_expression, ''), c.question), 500),
       COALESCE(NULLIF(c.asset_type, ''), 'UNKNOWN'),
       LEFT(COALESCE(NULLIF(c.asset_key, ''), c.clarification_id), 500),
       CASE c.selected_scope
           WHEN 'USER' THEN 'USER'
           WHEN 'PROJECT' THEN 'PROJECT_PENDING'
           ELSE 'QUERY'
       END,
       CASE c.selected_scope
           WHEN 'USER' THEN 'USER'
           WHEN 'PROJECT' THEN 'PROJECT_PENDING'
           ELSE 'QUERY'
       END,
       CASE WHEN c.selected_scope = 'USER' THEN c.answered_by ELSE NULL END,
       NULL::BIGINT
FROM qw_query_example qe
JOIN qw_runtime_clarification c ON c.run_id = qe.run_id AND c.status = 'ANSWERED'
WHERE qe.run_id IS NOT NULL
  AND c.selected_scope IN ('QUERY', 'USER', 'PROJECT')
ON CONFLICT DO NOTHING;

CREATE TABLE qw_semantic_sql_pattern (
    id VARCHAR(64) PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL,
    catalog_hash CHAR(64) NOT NULL,
    datasource_id INTEGER,
    semantic_shape_hash CHAR(64) NOT NULL,
    computation_shape_hash CHAR(64) NOT NULL,
    question_shape TEXT,
    sql_shape TEXT NOT NULL,
    quality_proof_json JSONB NOT NULL,
    binding_dependencies_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    usage_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    consecutive_failure_count BIGINT NOT NULL DEFAULT 0,
    quarantine_reason TEXT,
    source_run_id VARCHAR(64),
    source_attempt_id VARCHAR(64),
    last_used_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_semantic_sql_pattern UNIQUE(
        project_version_id, catalog_hash, datasource_id, semantic_shape_hash, computation_shape_hash, sql_shape
    )
);
CREATE INDEX idx_qw_semantic_sql_pattern_lookup
    ON qw_semantic_sql_pattern(project_id, project_version_id, catalog_hash, datasource_id, status);

CREATE TABLE qw_semantic_sql_pattern_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_id VARCHAR(64) NOT NULL REFERENCES qw_semantic_sql_pattern(id) ON DELETE CASCADE,
    run_id VARCHAR(64),
    event_type VARCHAR(32) NOT NULL,
    valid BOOLEAN NOT NULL DEFAULT TRUE,
    idempotency_key VARCHAR(200) NOT NULL UNIQUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_qw_semantic_sql_pattern_usage_pattern
    ON qw_semantic_sql_pattern_usage(pattern_id, valid, event_type);
