ALTER TABLE qw_semantic_material
    ADD COLUMN material_category VARCHAR(64) NOT NULL DEFAULT 'OTHER',
    ADD COLUMN lifecycle VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN';

CREATE INDEX idx_qw_semantic_material_category
    ON qw_semantic_material(project_version_id, material_category, lifecycle);

CREATE TABLE qw_project_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    material_id BIGINT NOT NULL REFERENCES qw_semantic_material(id) ON DELETE CASCADE,
    attempt_id BIGINT NOT NULL REFERENCES qw_semantic_material_attempt(id) ON DELETE CASCADE,
    evidence_type VARCHAR(64) NOT NULL,
    subject_key VARCHAR(500) NOT NULL,
    evidence_hash CHAR(64) NOT NULL,
    payload_json JSONB NOT NULL,
    confidence DECIMAL(6,4) NOT NULL,
    source_location VARCHAR(1000),
    extraction_model VARCHAR(255),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_project_evidence_attempt UNIQUE(attempt_id, evidence_type, subject_key, evidence_hash)
);

CREATE INDEX idx_qw_project_evidence_version
    ON qw_project_evidence(project_version_id, evidence_type, subject_key);
CREATE INDEX idx_qw_project_evidence_material
    ON qw_project_evidence(material_id, attempt_id);

CREATE TABLE qw_business_query_scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_version_id BIGINT NOT NULL REFERENCES qw_project_version(id) ON DELETE CASCADE,
    scenario_code VARCHAR(128) NOT NULL,
    business_name VARCHAR(500) NOT NULL,
    description TEXT,
    requirement_json JSONB NOT NULL,
    importance VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_material_id BIGINT REFERENCES qw_semantic_material(id) ON DELETE SET NULL,
    source_attempt_id BIGINT REFERENCES qw_semantic_material_attempt(id) ON DELETE SET NULL,
    source_location VARCHAR(1000),
    confidence DECIMAL(6,4) NOT NULL,
    scenario_fingerprint CHAR(64) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_qw_business_query_scenario_code UNIQUE(project_version_id, scenario_code),
    CONSTRAINT uk_qw_business_query_scenario_fingerprint UNIQUE(project_version_id, scenario_fingerprint)
);

CREATE INDEX idx_qw_business_query_scenario_active
    ON qw_business_query_scenario(project_version_id, status, importance);
CREATE INDEX idx_qw_business_query_scenario_source
    ON qw_business_query_scenario(source_material_id, source_attempt_id);
